### PR TITLE
Introduce Cobind typeclass and make Parser an instance of it.

### PR DESCRIPTION
**Pull request by b-studios**
For dicussion. Also see https://github.com/Toxaris/coalgebraic-parsing/commit/803305b0b50474064092fea1451ef00b068a0058#commitcomment-11757924

### CODE REVIEW

**Comment by Toxaris** [comment]
What's the status of these commits?
- I like the delegate family fo combinators.
- I don't understand the purpose of the Cobind typeclass.

So I propose to rearrange the commits and only merge the delegate stuff.

**Comment by b-studios** [comment]
The Cobind typeclass gives us some standard operators like `<<=` and `=<=`. These might be helpful (or not) once we deeply understood the semantics of delegate (== duplicate).

**Comment by b-studios** [comment]
In addition, so far we always followed the "implement all operations as instances of appropriate typeclasses" approach. Cobind sadly is only defined as one part of Comonad, so I inlined it here.

**Comment by Toxaris** [comment]
For me, the point of implementing operators as methods of _standard_ type classes is that there is existing code that works generically for all instances of the type class. By also supporting the type class, we can reuse this existing code. For example, by supporting Applicative for our parsers, we can use combinators like `traverse`.

This particular argument for type classes doesn't work for self-defined classes like CoBind.

**Comment by Toxaris** [comment]
Split into #4 and #6,closing.

**Pull request closed without merging**
